port = 50051

[geoip2.databases]
city = "test/data/GeoIP2-City-Test.mmdb"
country = "test/data/GeoIP2-Country-Test.mmdb"
enterprise = "test/data/GeoIP2-Enterprise-Test.mmdb"
anonymous_ip = "test/data/GeoIP2-Anonymous-IP-Test.mmdb"
asn = "test/data/GeoLite2-ASN-Test.mmdb"
connection_type = "test/data/GeoIP2-Connection-Type-Test.mmdb"
domain = "test/data/GeoIP2-Domain-Test.mmdb"
isp = "test/data/GeoIP2-ISP-Test.mmdb"

[redis]
urls = ["localhost:6379"]
